export * from './ChangePassword/ChangePassword';
export * from './CheckCode/CheckCode'
export * from './Dashboard/Dashboard'
export * from './ForgotPassword/ForgotPassword'
export * from './FromProfile/FormProfile'
export * from './Home/Home'
export * from './Login/Login'
export * from './Profile/Profile'
export * from './Register/Register'
